// Code generated by protoc-gen-go. DO NOT EDIT.
// source: auth.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	proto1 "github.com/microapis/users-api/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type AuthError struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthError) Reset()         { *m = AuthError{} }
func (m *AuthError) String() string { return proto.CompactTextString(m) }
func (*AuthError) ProtoMessage()    {}
func (*AuthError) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{0}
}

func (m *AuthError) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthError.Unmarshal(m, b)
}
func (m *AuthError) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthError.Marshal(b, m, deterministic)
}
func (m *AuthError) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthError.Merge(m, src)
}
func (m *AuthError) XXX_Size() int {
	return xxx_messageInfo_AuthError.Size(m)
}
func (m *AuthError) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthError.DiscardUnknown(m)
}

var xxx_messageInfo_AuthError proto.InternalMessageInfo

func (m *AuthError) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *AuthError) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type AuthMeta struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthMeta) Reset()         { *m = AuthMeta{} }
func (m *AuthMeta) String() string { return proto.CompactTextString(m) }
func (*AuthMeta) ProtoMessage()    {}
func (*AuthMeta) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{1}
}

func (m *AuthMeta) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthMeta.Unmarshal(m, b)
}
func (m *AuthMeta) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthMeta.Marshal(b, m, deterministic)
}
func (m *AuthMeta) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthMeta.Merge(m, src)
}
func (m *AuthMeta) XXX_Size() int {
	return xxx_messageInfo_AuthMeta.Size(m)
}
func (m *AuthMeta) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthMeta.DiscardUnknown(m)
}

var xxx_messageInfo_AuthMeta proto.InternalMessageInfo

type Auth struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId               string   `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Token                string   `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"`
	Blacklist            bool     `protobuf:"varint,4,opt,name=blacklist,proto3" json:"blacklist,omitempty"`
	Kind                 string   `protobuf:"bytes,5,opt,name=kind,proto3" json:"kind,omitempty"`
	CreatedAt            int64    `protobuf:"varint,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            int64    `protobuf:"varint,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Auth) Reset()         { *m = Auth{} }
func (m *Auth) String() string { return proto.CompactTextString(m) }
func (*Auth) ProtoMessage()    {}
func (*Auth) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{2}
}

func (m *Auth) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Auth.Unmarshal(m, b)
}
func (m *Auth) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Auth.Marshal(b, m, deterministic)
}
func (m *Auth) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Auth.Merge(m, src)
}
func (m *Auth) XXX_Size() int {
	return xxx_messageInfo_Auth.Size(m)
}
func (m *Auth) XXX_DiscardUnknown() {
	xxx_messageInfo_Auth.DiscardUnknown(m)
}

var xxx_messageInfo_Auth proto.InternalMessageInfo

func (m *Auth) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Auth) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *Auth) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *Auth) GetBlacklist() bool {
	if m != nil {
		return m.Blacklist
	}
	return false
}

func (m *Auth) GetKind() string {
	if m != nil {
		return m.Kind
	}
	return ""
}

func (m *Auth) GetCreatedAt() int64 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

func (m *Auth) GetUpdatedAt() int64 {
	if m != nil {
		return m.UpdatedAt
	}
	return 0
}

type AuthMetaToken struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	VerificationToken    string   `protobuf:"bytes,2,opt,name=verification_token,json=verificationToken,proto3" json:"verification_token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthMetaToken) Reset()         { *m = AuthMetaToken{} }
func (m *AuthMetaToken) String() string { return proto.CompactTextString(m) }
func (*AuthMetaToken) ProtoMessage()    {}
func (*AuthMetaToken) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{3}
}

func (m *AuthMetaToken) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthMetaToken.Unmarshal(m, b)
}
func (m *AuthMetaToken) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthMetaToken.Marshal(b, m, deterministic)
}
func (m *AuthMetaToken) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthMetaToken.Merge(m, src)
}
func (m *AuthMetaToken) XXX_Size() int {
	return xxx_messageInfo_AuthMetaToken.Size(m)
}
func (m *AuthMetaToken) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthMetaToken.DiscardUnknown(m)
}

var xxx_messageInfo_AuthMetaToken proto.InternalMessageInfo

func (m *AuthMetaToken) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *AuthMetaToken) GetVerificationToken() string {
	if m != nil {
		return m.VerificationToken
	}
	return ""
}

type AuthToken struct {
	Iat                  int64    `protobuf:"varint,1,opt,name=iat,proto3" json:"iat,omitempty"`
	Exp                  int64    `protobuf:"varint,2,opt,name=exp,proto3" json:"exp,omitempty"`
	UserId               string   `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthToken) Reset()         { *m = AuthToken{} }
func (m *AuthToken) String() string { return proto.CompactTextString(m) }
func (*AuthToken) ProtoMessage()    {}
func (*AuthToken) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{4}
}

func (m *AuthToken) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthToken.Unmarshal(m, b)
}
func (m *AuthToken) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthToken.Marshal(b, m, deterministic)
}
func (m *AuthToken) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthToken.Merge(m, src)
}
func (m *AuthToken) XXX_Size() int {
	return xxx_messageInfo_AuthToken.Size(m)
}
func (m *AuthToken) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthToken.DiscardUnknown(m)
}

var xxx_messageInfo_AuthToken proto.InternalMessageInfo

func (m *AuthToken) GetIat() int64 {
	if m != nil {
		return m.Iat
	}
	return 0
}

func (m *AuthToken) GetExp() int64 {
	if m != nil {
		return m.Exp
	}
	return 0
}

func (m *AuthToken) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

type AuthGetByTokenRequest struct {
	Token                string   `protobuf:"bytes,1,opt,name=Token,proto3" json:"Token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthGetByTokenRequest) Reset()         { *m = AuthGetByTokenRequest{} }
func (m *AuthGetByTokenRequest) String() string { return proto.CompactTextString(m) }
func (*AuthGetByTokenRequest) ProtoMessage()    {}
func (*AuthGetByTokenRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{5}
}

func (m *AuthGetByTokenRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthGetByTokenRequest.Unmarshal(m, b)
}
func (m *AuthGetByTokenRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthGetByTokenRequest.Marshal(b, m, deterministic)
}
func (m *AuthGetByTokenRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthGetByTokenRequest.Merge(m, src)
}
func (m *AuthGetByTokenRequest) XXX_Size() int {
	return xxx_messageInfo_AuthGetByTokenRequest.Size(m)
}
func (m *AuthGetByTokenRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthGetByTokenRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AuthGetByTokenRequest proto.InternalMessageInfo

func (m *AuthGetByTokenRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type AuthGetByTokenResponse struct {
	Data                 *Auth      `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Meta                 *AuthMeta  `protobuf:"bytes,2,opt,name=meta,proto3" json:"meta,omitempty"`
	Error                *AuthError `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *AuthGetByTokenResponse) Reset()         { *m = AuthGetByTokenResponse{} }
func (m *AuthGetByTokenResponse) String() string { return proto.CompactTextString(m) }
func (*AuthGetByTokenResponse) ProtoMessage()    {}
func (*AuthGetByTokenResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{6}
}

func (m *AuthGetByTokenResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthGetByTokenResponse.Unmarshal(m, b)
}
func (m *AuthGetByTokenResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthGetByTokenResponse.Marshal(b, m, deterministic)
}
func (m *AuthGetByTokenResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthGetByTokenResponse.Merge(m, src)
}
func (m *AuthGetByTokenResponse) XXX_Size() int {
	return xxx_messageInfo_AuthGetByTokenResponse.Size(m)
}
func (m *AuthGetByTokenResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthGetByTokenResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AuthGetByTokenResponse proto.InternalMessageInfo

func (m *AuthGetByTokenResponse) GetData() *Auth {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *AuthGetByTokenResponse) GetMeta() *AuthMeta {
	if m != nil {
		return m.Meta
	}
	return nil
}

func (m *AuthGetByTokenResponse) GetError() *AuthError {
	if m != nil {
		return m.Error
	}
	return nil
}

type AuthLoginRequest struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthLoginRequest) Reset()         { *m = AuthLoginRequest{} }
func (m *AuthLoginRequest) String() string { return proto.CompactTextString(m) }
func (*AuthLoginRequest) ProtoMessage()    {}
func (*AuthLoginRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{7}
}

func (m *AuthLoginRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthLoginRequest.Unmarshal(m, b)
}
func (m *AuthLoginRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthLoginRequest.Marshal(b, m, deterministic)
}
func (m *AuthLoginRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthLoginRequest.Merge(m, src)
}
func (m *AuthLoginRequest) XXX_Size() int {
	return xxx_messageInfo_AuthLoginRequest.Size(m)
}
func (m *AuthLoginRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthLoginRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AuthLoginRequest proto.InternalMessageInfo

func (m *AuthLoginRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *AuthLoginRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type AuthLoginResponse struct {
	Data                 *proto1.User   `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Meta                 *AuthMetaToken `protobuf:"bytes,2,opt,name=meta,proto3" json:"meta,omitempty"`
	Error                *AuthError     `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *AuthLoginResponse) Reset()         { *m = AuthLoginResponse{} }
func (m *AuthLoginResponse) String() string { return proto.CompactTextString(m) }
func (*AuthLoginResponse) ProtoMessage()    {}
func (*AuthLoginResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{8}
}

func (m *AuthLoginResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthLoginResponse.Unmarshal(m, b)
}
func (m *AuthLoginResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthLoginResponse.Marshal(b, m, deterministic)
}
func (m *AuthLoginResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthLoginResponse.Merge(m, src)
}
func (m *AuthLoginResponse) XXX_Size() int {
	return xxx_messageInfo_AuthLoginResponse.Size(m)
}
func (m *AuthLoginResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthLoginResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AuthLoginResponse proto.InternalMessageInfo

func (m *AuthLoginResponse) GetData() *proto1.User {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *AuthLoginResponse) GetMeta() *AuthMetaToken {
	if m != nil {
		return m.Meta
	}
	return nil
}

func (m *AuthLoginResponse) GetError() *AuthError {
	if m != nil {
		return m.Error
	}
	return nil
}

type AuthSignupRequest struct {
	User                 *proto1.User `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *AuthSignupRequest) Reset()         { *m = AuthSignupRequest{} }
func (m *AuthSignupRequest) String() string { return proto.CompactTextString(m) }
func (*AuthSignupRequest) ProtoMessage()    {}
func (*AuthSignupRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{9}
}

func (m *AuthSignupRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthSignupRequest.Unmarshal(m, b)
}
func (m *AuthSignupRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthSignupRequest.Marshal(b, m, deterministic)
}
func (m *AuthSignupRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthSignupRequest.Merge(m, src)
}
func (m *AuthSignupRequest) XXX_Size() int {
	return xxx_messageInfo_AuthSignupRequest.Size(m)
}
func (m *AuthSignupRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthSignupRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AuthSignupRequest proto.InternalMessageInfo

func (m *AuthSignupRequest) GetUser() *proto1.User {
	if m != nil {
		return m.User
	}
	return nil
}

type AuthSignupResponse struct {
	Data                 *proto1.User   `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Meta                 *AuthMetaToken `protobuf:"bytes,2,opt,name=meta,proto3" json:"meta,omitempty"`
	Error                *AuthError     `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *AuthSignupResponse) Reset()         { *m = AuthSignupResponse{} }
func (m *AuthSignupResponse) String() string { return proto.CompactTextString(m) }
func (*AuthSignupResponse) ProtoMessage()    {}
func (*AuthSignupResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{10}
}

func (m *AuthSignupResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthSignupResponse.Unmarshal(m, b)
}
func (m *AuthSignupResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthSignupResponse.Marshal(b, m, deterministic)
}
func (m *AuthSignupResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthSignupResponse.Merge(m, src)
}
func (m *AuthSignupResponse) XXX_Size() int {
	return xxx_messageInfo_AuthSignupResponse.Size(m)
}
func (m *AuthSignupResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthSignupResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AuthSignupResponse proto.InternalMessageInfo

func (m *AuthSignupResponse) GetData() *proto1.User {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *AuthSignupResponse) GetMeta() *AuthMetaToken {
	if m != nil {
		return m.Meta
	}
	return nil
}

func (m *AuthSignupResponse) GetError() *AuthError {
	if m != nil {
		return m.Error
	}
	return nil
}

type AuthVerifyTokenRequest struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Kind                 string   `protobuf:"bytes,2,opt,name=kind,proto3" json:"kind,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthVerifyTokenRequest) Reset()         { *m = AuthVerifyTokenRequest{} }
func (m *AuthVerifyTokenRequest) String() string { return proto.CompactTextString(m) }
func (*AuthVerifyTokenRequest) ProtoMessage()    {}
func (*AuthVerifyTokenRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{11}
}

func (m *AuthVerifyTokenRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthVerifyTokenRequest.Unmarshal(m, b)
}
func (m *AuthVerifyTokenRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthVerifyTokenRequest.Marshal(b, m, deterministic)
}
func (m *AuthVerifyTokenRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthVerifyTokenRequest.Merge(m, src)
}
func (m *AuthVerifyTokenRequest) XXX_Size() int {
	return xxx_messageInfo_AuthVerifyTokenRequest.Size(m)
}
func (m *AuthVerifyTokenRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthVerifyTokenRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AuthVerifyTokenRequest proto.InternalMessageInfo

func (m *AuthVerifyTokenRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *AuthVerifyTokenRequest) GetKind() string {
	if m != nil {
		return m.Kind
	}
	return ""
}

type AuthVerifyTokenResponse struct {
	Data                 *AuthToken `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Error                *AuthError `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *AuthVerifyTokenResponse) Reset()         { *m = AuthVerifyTokenResponse{} }
func (m *AuthVerifyTokenResponse) String() string { return proto.CompactTextString(m) }
func (*AuthVerifyTokenResponse) ProtoMessage()    {}
func (*AuthVerifyTokenResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{12}
}

func (m *AuthVerifyTokenResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthVerifyTokenResponse.Unmarshal(m, b)
}
func (m *AuthVerifyTokenResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthVerifyTokenResponse.Marshal(b, m, deterministic)
}
func (m *AuthVerifyTokenResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthVerifyTokenResponse.Merge(m, src)
}
func (m *AuthVerifyTokenResponse) XXX_Size() int {
	return xxx_messageInfo_AuthVerifyTokenResponse.Size(m)
}
func (m *AuthVerifyTokenResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthVerifyTokenResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AuthVerifyTokenResponse proto.InternalMessageInfo

func (m *AuthVerifyTokenResponse) GetData() *AuthToken {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *AuthVerifyTokenResponse) GetError() *AuthError {
	if m != nil {
		return m.Error
	}
	return nil
}

type AuthVerifyEmailRequest struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthVerifyEmailRequest) Reset()         { *m = AuthVerifyEmailRequest{} }
func (m *AuthVerifyEmailRequest) String() string { return proto.CompactTextString(m) }
func (*AuthVerifyEmailRequest) ProtoMessage()    {}
func (*AuthVerifyEmailRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{13}
}

func (m *AuthVerifyEmailRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthVerifyEmailRequest.Unmarshal(m, b)
}
func (m *AuthVerifyEmailRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthVerifyEmailRequest.Marshal(b, m, deterministic)
}
func (m *AuthVerifyEmailRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthVerifyEmailRequest.Merge(m, src)
}
func (m *AuthVerifyEmailRequest) XXX_Size() int {
	return xxx_messageInfo_AuthVerifyEmailRequest.Size(m)
}
func (m *AuthVerifyEmailRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthVerifyEmailRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AuthVerifyEmailRequest proto.InternalMessageInfo

func (m *AuthVerifyEmailRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type AuthVerifyEmailResponse struct {
	Error                *AuthError `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *AuthVerifyEmailResponse) Reset()         { *m = AuthVerifyEmailResponse{} }
func (m *AuthVerifyEmailResponse) String() string { return proto.CompactTextString(m) }
func (*AuthVerifyEmailResponse) ProtoMessage()    {}
func (*AuthVerifyEmailResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{14}
}

func (m *AuthVerifyEmailResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthVerifyEmailResponse.Unmarshal(m, b)
}
func (m *AuthVerifyEmailResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthVerifyEmailResponse.Marshal(b, m, deterministic)
}
func (m *AuthVerifyEmailResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthVerifyEmailResponse.Merge(m, src)
}
func (m *AuthVerifyEmailResponse) XXX_Size() int {
	return xxx_messageInfo_AuthVerifyEmailResponse.Size(m)
}
func (m *AuthVerifyEmailResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthVerifyEmailResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AuthVerifyEmailResponse proto.InternalMessageInfo

func (m *AuthVerifyEmailResponse) GetError() *AuthError {
	if m != nil {
		return m.Error
	}
	return nil
}

type AuthLogoutRequest struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthLogoutRequest) Reset()         { *m = AuthLogoutRequest{} }
func (m *AuthLogoutRequest) String() string { return proto.CompactTextString(m) }
func (*AuthLogoutRequest) ProtoMessage()    {}
func (*AuthLogoutRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{15}
}

func (m *AuthLogoutRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthLogoutRequest.Unmarshal(m, b)
}
func (m *AuthLogoutRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthLogoutRequest.Marshal(b, m, deterministic)
}
func (m *AuthLogoutRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthLogoutRequest.Merge(m, src)
}
func (m *AuthLogoutRequest) XXX_Size() int {
	return xxx_messageInfo_AuthLogoutRequest.Size(m)
}
func (m *AuthLogoutRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthLogoutRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AuthLogoutRequest proto.InternalMessageInfo

func (m *AuthLogoutRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type AuthLogoutResponse struct {
	Error                *AuthError `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *AuthLogoutResponse) Reset()         { *m = AuthLogoutResponse{} }
func (m *AuthLogoutResponse) String() string { return proto.CompactTextString(m) }
func (*AuthLogoutResponse) ProtoMessage()    {}
func (*AuthLogoutResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{16}
}

func (m *AuthLogoutResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthLogoutResponse.Unmarshal(m, b)
}
func (m *AuthLogoutResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthLogoutResponse.Marshal(b, m, deterministic)
}
func (m *AuthLogoutResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthLogoutResponse.Merge(m, src)
}
func (m *AuthLogoutResponse) XXX_Size() int {
	return xxx_messageInfo_AuthLogoutResponse.Size(m)
}
func (m *AuthLogoutResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthLogoutResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AuthLogoutResponse proto.InternalMessageInfo

func (m *AuthLogoutResponse) GetError() *AuthError {
	if m != nil {
		return m.Error
	}
	return nil
}

type AuthForgotPasswordRequest struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthForgotPasswordRequest) Reset()         { *m = AuthForgotPasswordRequest{} }
func (m *AuthForgotPasswordRequest) String() string { return proto.CompactTextString(m) }
func (*AuthForgotPasswordRequest) ProtoMessage()    {}
func (*AuthForgotPasswordRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{17}
}

func (m *AuthForgotPasswordRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthForgotPasswordRequest.Unmarshal(m, b)
}
func (m *AuthForgotPasswordRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthForgotPasswordRequest.Marshal(b, m, deterministic)
}
func (m *AuthForgotPasswordRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthForgotPasswordRequest.Merge(m, src)
}
func (m *AuthForgotPasswordRequest) XXX_Size() int {
	return xxx_messageInfo_AuthForgotPasswordRequest.Size(m)
}
func (m *AuthForgotPasswordRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthForgotPasswordRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AuthForgotPasswordRequest proto.InternalMessageInfo

func (m *AuthForgotPasswordRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

type AuthForgotPasswordResponse struct {
	Data                 *AuthMetaToken `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Meta                 *AuthMeta      `protobuf:"bytes,2,opt,name=meta,proto3" json:"meta,omitempty"`
	Error                *AuthError     `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *AuthForgotPasswordResponse) Reset()         { *m = AuthForgotPasswordResponse{} }
func (m *AuthForgotPasswordResponse) String() string { return proto.CompactTextString(m) }
func (*AuthForgotPasswordResponse) ProtoMessage()    {}
func (*AuthForgotPasswordResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{18}
}

func (m *AuthForgotPasswordResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthForgotPasswordResponse.Unmarshal(m, b)
}
func (m *AuthForgotPasswordResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthForgotPasswordResponse.Marshal(b, m, deterministic)
}
func (m *AuthForgotPasswordResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthForgotPasswordResponse.Merge(m, src)
}
func (m *AuthForgotPasswordResponse) XXX_Size() int {
	return xxx_messageInfo_AuthForgotPasswordResponse.Size(m)
}
func (m *AuthForgotPasswordResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthForgotPasswordResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AuthForgotPasswordResponse proto.InternalMessageInfo

func (m *AuthForgotPasswordResponse) GetData() *AuthMetaToken {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *AuthForgotPasswordResponse) GetMeta() *AuthMeta {
	if m != nil {
		return m.Meta
	}
	return nil
}

func (m *AuthForgotPasswordResponse) GetError() *AuthError {
	if m != nil {
		return m.Error
	}
	return nil
}

type AuthRecoverPasswordRequest struct {
	NewPassword          string   `protobuf:"bytes,1,opt,name=new_password,json=newPassword,proto3" json:"new_password,omitempty"`
	Token                string   `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthRecoverPasswordRequest) Reset()         { *m = AuthRecoverPasswordRequest{} }
func (m *AuthRecoverPasswordRequest) String() string { return proto.CompactTextString(m) }
func (*AuthRecoverPasswordRequest) ProtoMessage()    {}
func (*AuthRecoverPasswordRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{19}
}

func (m *AuthRecoverPasswordRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthRecoverPasswordRequest.Unmarshal(m, b)
}
func (m *AuthRecoverPasswordRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthRecoverPasswordRequest.Marshal(b, m, deterministic)
}
func (m *AuthRecoverPasswordRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthRecoverPasswordRequest.Merge(m, src)
}
func (m *AuthRecoverPasswordRequest) XXX_Size() int {
	return xxx_messageInfo_AuthRecoverPasswordRequest.Size(m)
}
func (m *AuthRecoverPasswordRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthRecoverPasswordRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AuthRecoverPasswordRequest proto.InternalMessageInfo

func (m *AuthRecoverPasswordRequest) GetNewPassword() string {
	if m != nil {
		return m.NewPassword
	}
	return ""
}

func (m *AuthRecoverPasswordRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type AuthRecoverPasswordResponse struct {
	Error                *AuthError `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *AuthRecoverPasswordResponse) Reset()         { *m = AuthRecoverPasswordResponse{} }
func (m *AuthRecoverPasswordResponse) String() string { return proto.CompactTextString(m) }
func (*AuthRecoverPasswordResponse) ProtoMessage()    {}
func (*AuthRecoverPasswordResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{20}
}

func (m *AuthRecoverPasswordResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthRecoverPasswordResponse.Unmarshal(m, b)
}
func (m *AuthRecoverPasswordResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthRecoverPasswordResponse.Marshal(b, m, deterministic)
}
func (m *AuthRecoverPasswordResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthRecoverPasswordResponse.Merge(m, src)
}
func (m *AuthRecoverPasswordResponse) XXX_Size() int {
	return xxx_messageInfo_AuthRecoverPasswordResponse.Size(m)
}
func (m *AuthRecoverPasswordResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthRecoverPasswordResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AuthRecoverPasswordResponse proto.InternalMessageInfo

func (m *AuthRecoverPasswordResponse) GetError() *AuthError {
	if m != nil {
		return m.Error
	}
	return nil
}

func init() {
	proto.RegisterType((*AuthError)(nil), "proto.AuthError")
	proto.RegisterType((*AuthMeta)(nil), "proto.AuthMeta")
	proto.RegisterType((*Auth)(nil), "proto.Auth")
	proto.RegisterType((*AuthMetaToken)(nil), "proto.AuthMetaToken")
	proto.RegisterType((*AuthToken)(nil), "proto.AuthToken")
	proto.RegisterType((*AuthGetByTokenRequest)(nil), "proto.AuthGetByTokenRequest")
	proto.RegisterType((*AuthGetByTokenResponse)(nil), "proto.AuthGetByTokenResponse")
	proto.RegisterType((*AuthLoginRequest)(nil), "proto.AuthLoginRequest")
	proto.RegisterType((*AuthLoginResponse)(nil), "proto.AuthLoginResponse")
	proto.RegisterType((*AuthSignupRequest)(nil), "proto.AuthSignupRequest")
	proto.RegisterType((*AuthSignupResponse)(nil), "proto.AuthSignupResponse")
	proto.RegisterType((*AuthVerifyTokenRequest)(nil), "proto.AuthVerifyTokenRequest")
	proto.RegisterType((*AuthVerifyTokenResponse)(nil), "proto.AuthVerifyTokenResponse")
	proto.RegisterType((*AuthVerifyEmailRequest)(nil), "proto.AuthVerifyEmailRequest")
	proto.RegisterType((*AuthVerifyEmailResponse)(nil), "proto.AuthVerifyEmailResponse")
	proto.RegisterType((*AuthLogoutRequest)(nil), "proto.AuthLogoutRequest")
	proto.RegisterType((*AuthLogoutResponse)(nil), "proto.AuthLogoutResponse")
	proto.RegisterType((*AuthForgotPasswordRequest)(nil), "proto.AuthForgotPasswordRequest")
	proto.RegisterType((*AuthForgotPasswordResponse)(nil), "proto.AuthForgotPasswordResponse")
	proto.RegisterType((*AuthRecoverPasswordRequest)(nil), "proto.AuthRecoverPasswordRequest")
	proto.RegisterType((*AuthRecoverPasswordResponse)(nil), "proto.AuthRecoverPasswordResponse")
}

func init() {
	proto.RegisterFile("auth.proto", fileDescriptor_8bbd6f3875b0e874)
}

var fileDescriptor_8bbd6f3875b0e874 = []byte{
	// 784 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xc4, 0x54, 0xdd, 0x6e, 0xd3, 0x30,
	0x14, 0x5e, 0xfa, 0xb7, 0xf5, 0x14, 0xf6, 0x63, 0x0d, 0x96, 0x85, 0x8d, 0x75, 0x06, 0xa1, 0x72,
	0xb1, 0x0e, 0x0a, 0x37, 0x48, 0x93, 0x50, 0x27, 0xc6, 0x8f, 0xf8, 0x11, 0x0a, 0x1b, 0x48, 0xdc,
	0x54, 0x5e, 0x62, 0x3a, 0x6b, 0x6b, 0x1d, 0x12, 0x67, 0x83, 0x17, 0x80, 0x07, 0xe0, 0x59, 0x78,
	0x2e, 0x5e, 0x01, 0xd9, 0x4e, 0x52, 0xa7, 0xcd, 0x22, 0x4d, 0x42, 0xe2, 0x2a, 0xb6, 0xcf, 0x77,
	0x8e, 0xbf, 0xef, 0xe4, 0x7c, 0x06, 0x20, 0xb1, 0x38, 0xe9, 0x06, 0x21, 0x17, 0x1c, 0xd5, 0xd5,
	0xc7, 0x79, 0x30, 0x64, 0xe2, 0x24, 0x3e, 0xee, 0x7a, 0x7c, 0xb4, 0x3b, 0x62, 0x5e, 0xc8, 0x49,
	0xc0, 0xa2, 0xdd, 0x38, 0xa2, 0x61, 0xb4, 0x43, 0x02, 0xb6, 0xab, 0x50, 0x7a, 0xaf, 0x13, 0xf1,
	0x13, 0x68, 0xf6, 0x63, 0x71, 0x72, 0x10, 0x86, 0x3c, 0x44, 0x08, 0x6a, 0x1e, 0xf7, 0xa9, 0x6d,
	0xb5, 0xad, 0x4e, 0xdd, 0x55, 0x6b, 0x64, 0xc3, 0xfc, 0x88, 0x46, 0x11, 0x19, 0x52, 0xbb, 0xd2,
	0xb6, 0x3a, 0x4d, 0x37, 0xdd, 0x62, 0x80, 0x05, 0x99, 0xfa, 0x96, 0x0a, 0x82, 0x7f, 0x5b, 0x50,
	0x93, 0x1b, 0xb4, 0x08, 0x15, 0xe6, 0xab, 0x02, 0x4d, 0xb7, 0xc2, 0x7c, 0xb4, 0x06, 0xf3, 0xf2,
	0xba, 0x01, 0xf3, 0x93, 0xf4, 0x86, 0xdc, 0xbe, 0xf2, 0xd1, 0x2a, 0xd4, 0x05, 0x3f, 0xa5, 0x63,
	0xbb, 0xaa, 0x8e, 0xf5, 0x06, 0x6d, 0x40, 0xf3, 0xf8, 0x8c, 0x78, 0xa7, 0x67, 0x2c, 0x12, 0x76,
	0xad, 0x6d, 0x75, 0x16, 0xdc, 0xc9, 0x81, 0xe4, 0x77, 0xca, 0xc6, 0xbe, 0x5d, 0x57, 0x29, 0x6a,
	0x8d, 0x36, 0x01, 0xbc, 0x90, 0x12, 0x41, 0xfd, 0x01, 0x11, 0x76, 0xa3, 0x6d, 0x75, 0xaa, 0x6e,
	0x33, 0x39, 0xe9, 0x0b, 0x19, 0x8e, 0x03, 0x3f, 0x0d, 0xcf, 0xeb, 0x70, 0x72, 0xd2, 0x17, 0xf8,
	0x10, 0xae, 0xa7, 0x1a, 0x0e, 0x15, 0x81, 0x8c, 0x96, 0x65, 0xd2, 0xda, 0x01, 0x74, 0x4e, 0x43,
	0xf6, 0x85, 0x79, 0x44, 0x30, 0x3e, 0x1e, 0x68, 0x88, 0x16, 0xb4, 0x62, 0x46, 0x54, 0x11, 0xfc,
	0x52, 0x37, 0x55, 0x57, 0x5c, 0x86, 0x2a, 0x23, 0x42, 0xd5, 0xab, 0xba, 0x72, 0x29, 0x4f, 0xe8,
	0xb7, 0x40, 0xa5, 0x57, 0x5d, 0xb9, 0x34, 0xbb, 0x54, 0x35, 0xbb, 0x84, 0x77, 0xe0, 0x86, 0xac,
	0xf4, 0x82, 0x8a, 0xfd, 0xef, 0xaa, 0x9c, 0x4b, 0xbf, 0xc6, 0x34, 0x12, 0x92, 0xe7, 0xa1, 0xc9,
	0x53, 0x5f, 0xfc, 0xc3, 0x82, 0x9b, 0xd3, 0xf8, 0x28, 0xe0, 0xe3, 0x88, 0xa2, 0x2d, 0xa8, 0xf9,
	0x44, 0x10, 0x85, 0x6f, 0xf5, 0x5a, 0xfa, 0xf7, 0x77, 0x25, 0xd8, 0x55, 0x01, 0x74, 0x07, 0x6a,
	0x23, 0x2a, 0x88, 0xa2, 0xd5, 0xea, 0x2d, 0x19, 0x00, 0xd9, 0x1d, 0x57, 0x05, 0xd1, 0x3d, 0xa8,
	0x53, 0x39, 0x2a, 0x8a, 0x66, 0xab, 0xb7, 0x6c, 0xa0, 0xd4, 0x08, 0xb9, 0x3a, 0x8c, 0x9f, 0xc1,
	0xb2, 0x3c, 0x7b, 0xc3, 0x87, 0xcc, 0xa4, 0x4c, 0x47, 0x84, 0x9d, 0xa5, 0x94, 0xd5, 0x06, 0x39,
	0xb0, 0x10, 0x90, 0x28, 0xba, 0xe0, 0x61, 0x3a, 0x21, 0xd9, 0x5e, 0xca, 0x59, 0x31, 0xca, 0x94,
	0x2a, 0x39, 0x8a, 0x68, 0x98, 0x28, 0xe9, 0xe4, 0x94, 0xac, 0x4e, 0x29, 0xd1, 0x6d, 0xb9, 0x9a,
	0x9c, 0xc7, 0x9a, 0xc7, 0x07, 0x36, 0x1c, 0xc7, 0x41, 0xaa, 0x67, 0x0b, 0x6a, 0xf2, 0x2f, 0x15,
	0xf2, 0x90, 0x01, 0xfc, 0xd3, 0x02, 0x64, 0xa6, 0xfd, 0x3f, 0xfe, 0xfb, 0x7a, 0x2c, 0x3e, 0xca,
	0x49, 0x9d, 0x99, 0xa3, 0x82, 0x79, 0x4f, 0x8d, 0x56, 0x99, 0x18, 0x0d, 0x0f, 0x61, 0x6d, 0xa6,
	0x46, 0xa2, 0xe8, 0x6e, 0x4e, 0x91, 0xc9, 0x22, 0x21, 0xab, 0x64, 0x65, 0x64, 0x2b, 0xe5, 0x64,
	0xbb, 0x26, 0xd9, 0x03, 0x39, 0x24, 0xa5, 0x64, 0x71, 0xdf, 0x24, 0x96, 0xe0, 0x13, 0x62, 0xd9,
	0x95, 0x56, 0xf9, 0x95, 0xf7, 0xb3, 0x39, 0xe3, 0xb1, 0x28, 0xbf, 0x6d, 0x4f, 0xff, 0xd3, 0x14,
	0x7a, 0xc5, 0x8b, 0x1e, 0xc2, 0xba, 0x3c, 0x7b, 0xce, 0xc3, 0x21, 0x17, 0xef, 0x93, 0x39, 0x2f,
	0x35, 0x08, 0xfe, 0x65, 0x81, 0x53, 0x94, 0x93, 0xdc, 0xdc, 0xc9, 0xf5, 0xfe, 0x92, 0x61, 0xf9,
	0xf7, 0x06, 0x3f, 0xd2, 0xa4, 0x5c, 0xea, 0xf1, 0x73, 0x1a, 0x4e, 0x2b, 0xd9, 0x86, 0x6b, 0x63,
	0x7a, 0x31, 0xc8, 0x8c, 0xad, 0x05, 0xb5, 0xc6, 0xf4, 0x22, 0x45, 0x4e, 0xba, 0x5b, 0x31, 0xbb,
	0x7b, 0x00, 0xb7, 0x0a, 0xcb, 0x5e, 0xad, 0xcd, 0xbd, 0x3f, 0x35, 0x68, 0x29, 0xe7, 0xd1, 0xf0,
	0x9c, 0x79, 0x14, 0xbd, 0x06, 0x98, 0x3c, 0x89, 0x68, 0xc3, 0x48, 0x9b, 0x79, 0x59, 0x9d, 0xcd,
	0x4b, 0xa2, 0x9a, 0x02, 0x9e, 0x43, 0x7b, 0x50, 0x57, 0x0f, 0x12, 0x5a, 0x33, 0x90, 0xe6, 0x4b,
	0xe7, 0xd8, 0xb3, 0x81, 0x2c, 0xfb, 0x29, 0x34, 0xf4, 0x7b, 0x80, 0x4c, 0x54, 0xee, 0x65, 0x71,
	0xd6, 0x0b, 0x22, 0x59, 0x81, 0x77, 0xd0, 0x32, 0x3c, 0x88, 0x4c, 0xba, 0xb3, 0xfe, 0x76, 0x6e,
	0x5f, 0x16, 0x9e, 0xad, 0xa7, 0xac, 0x53, 0x50, 0xcf, 0xb4, 0x60, 0x41, 0xbd, 0x9c, 0xe3, 0xb4,
	0x40, 0x6d, 0x0e, 0x34, 0xd5, 0x86, 0x89, 0xb5, 0x72, 0x02, 0xf3, 0x4e, 0xc2, 0x73, 0xe8, 0x13,
	0x2c, 0xe6, 0x67, 0x1d, 0xb5, 0x0d, 0x78, 0xa1, 0x75, 0x9c, 0xed, 0x12, 0x44, 0x56, 0xf8, 0x33,
	0x2c, 0x4d, 0x0d, 0x16, 0x32, 0xf3, 0x8a, 0x67, 0xd9, 0xc1, 0x65, 0x90, 0xb4, 0xf6, 0x71, 0x43,
	0x81, 0x1e, 0xfd, 0x0d, 0x00, 0x00, 0xff, 0xff, 0x04, 0x5d, 0x67, 0xca, 0x95, 0x09, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// AuthServiceClient is the client API for AuthService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AuthServiceClient interface {
	GetByToken(ctx context.Context, in *AuthGetByTokenRequest, opts ...grpc.CallOption) (*AuthGetByTokenResponse, error)
	Login(ctx context.Context, in *AuthLoginRequest, opts ...grpc.CallOption) (*AuthLoginResponse, error)
	Signup(ctx context.Context, in *AuthSignupRequest, opts ...grpc.CallOption) (*AuthSignupResponse, error)
	VerifyToken(ctx context.Context, in *AuthVerifyTokenRequest, opts ...grpc.CallOption) (*AuthVerifyTokenResponse, error)
	VerifyEmail(ctx context.Context, in *AuthVerifyEmailRequest, opts ...grpc.CallOption) (*AuthVerifyEmailResponse, error)
	Logout(ctx context.Context, in *AuthLogoutRequest, opts ...grpc.CallOption) (*AuthLogoutResponse, error)
	ForgotPassword(ctx context.Context, in *AuthForgotPasswordRequest, opts ...grpc.CallOption) (*AuthForgotPasswordResponse, error)
	RecoverPassword(ctx context.Context, in *AuthRecoverPasswordRequest, opts ...grpc.CallOption) (*AuthRecoverPasswordResponse, error)
}

type authServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAuthServiceClient(cc grpc.ClientConnInterface) AuthServiceClient {
	return &authServiceClient{cc}
}

func (c *authServiceClient) GetByToken(ctx context.Context, in *AuthGetByTokenRequest, opts ...grpc.CallOption) (*AuthGetByTokenResponse, error) {
	out := new(AuthGetByTokenResponse)
	err := c.cc.Invoke(ctx, "/proto.AuthService/GetByToken", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) Login(ctx context.Context, in *AuthLoginRequest, opts ...grpc.CallOption) (*AuthLoginResponse, error) {
	out := new(AuthLoginResponse)
	err := c.cc.Invoke(ctx, "/proto.AuthService/Login", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) Signup(ctx context.Context, in *AuthSignupRequest, opts ...grpc.CallOption) (*AuthSignupResponse, error) {
	out := new(AuthSignupResponse)
	err := c.cc.Invoke(ctx, "/proto.AuthService/Signup", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) VerifyToken(ctx context.Context, in *AuthVerifyTokenRequest, opts ...grpc.CallOption) (*AuthVerifyTokenResponse, error) {
	out := new(AuthVerifyTokenResponse)
	err := c.cc.Invoke(ctx, "/proto.AuthService/VerifyToken", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) VerifyEmail(ctx context.Context, in *AuthVerifyEmailRequest, opts ...grpc.CallOption) (*AuthVerifyEmailResponse, error) {
	out := new(AuthVerifyEmailResponse)
	err := c.cc.Invoke(ctx, "/proto.AuthService/VerifyEmail", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) Logout(ctx context.Context, in *AuthLogoutRequest, opts ...grpc.CallOption) (*AuthLogoutResponse, error) {
	out := new(AuthLogoutResponse)
	err := c.cc.Invoke(ctx, "/proto.AuthService/Logout", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) ForgotPassword(ctx context.Context, in *AuthForgotPasswordRequest, opts ...grpc.CallOption) (*AuthForgotPasswordResponse, error) {
	out := new(AuthForgotPasswordResponse)
	err := c.cc.Invoke(ctx, "/proto.AuthService/ForgotPassword", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) RecoverPassword(ctx context.Context, in *AuthRecoverPasswordRequest, opts ...grpc.CallOption) (*AuthRecoverPasswordResponse, error) {
	out := new(AuthRecoverPasswordResponse)
	err := c.cc.Invoke(ctx, "/proto.AuthService/RecoverPassword", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuthServiceServer is the server API for AuthService service.
type AuthServiceServer interface {
	GetByToken(context.Context, *AuthGetByTokenRequest) (*AuthGetByTokenResponse, error)
	Login(context.Context, *AuthLoginRequest) (*AuthLoginResponse, error)
	Signup(context.Context, *AuthSignupRequest) (*AuthSignupResponse, error)
	VerifyToken(context.Context, *AuthVerifyTokenRequest) (*AuthVerifyTokenResponse, error)
	VerifyEmail(context.Context, *AuthVerifyEmailRequest) (*AuthVerifyEmailResponse, error)
	Logout(context.Context, *AuthLogoutRequest) (*AuthLogoutResponse, error)
	ForgotPassword(context.Context, *AuthForgotPasswordRequest) (*AuthForgotPasswordResponse, error)
	RecoverPassword(context.Context, *AuthRecoverPasswordRequest) (*AuthRecoverPasswordResponse, error)
}

// UnimplementedAuthServiceServer can be embedded to have forward compatible implementations.
type UnimplementedAuthServiceServer struct {
}

func (*UnimplementedAuthServiceServer) GetByToken(ctx context.Context, req *AuthGetByTokenRequest) (*AuthGetByTokenResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetByToken not implemented")
}
func (*UnimplementedAuthServiceServer) Login(ctx context.Context, req *AuthLoginRequest) (*AuthLoginResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Login not implemented")
}
func (*UnimplementedAuthServiceServer) Signup(ctx context.Context, req *AuthSignupRequest) (*AuthSignupResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Signup not implemented")
}
func (*UnimplementedAuthServiceServer) VerifyToken(ctx context.Context, req *AuthVerifyTokenRequest) (*AuthVerifyTokenResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method VerifyToken not implemented")
}
func (*UnimplementedAuthServiceServer) VerifyEmail(ctx context.Context, req *AuthVerifyEmailRequest) (*AuthVerifyEmailResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method VerifyEmail not implemented")
}
func (*UnimplementedAuthServiceServer) Logout(ctx context.Context, req *AuthLogoutRequest) (*AuthLogoutResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Logout not implemented")
}
func (*UnimplementedAuthServiceServer) ForgotPassword(ctx context.Context, req *AuthForgotPasswordRequest) (*AuthForgotPasswordResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ForgotPassword not implemented")
}
func (*UnimplementedAuthServiceServer) RecoverPassword(ctx context.Context, req *AuthRecoverPasswordRequest) (*AuthRecoverPasswordResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RecoverPassword not implemented")
}

func RegisterAuthServiceServer(s *grpc.Server, srv AuthServiceServer) {
	s.RegisterService(&_AuthService_serviceDesc, srv)
}

func _AuthService_GetByToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthGetByTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).GetByToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.AuthService/GetByToken",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).GetByToken(ctx, req.(*AuthGetByTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthLoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.AuthService/Login",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).Login(ctx, req.(*AuthLoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_Signup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthSignupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).Signup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.AuthService/Signup",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).Signup(ctx, req.(*AuthSignupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_VerifyToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthVerifyTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).VerifyToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.AuthService/VerifyToken",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).VerifyToken(ctx, req.(*AuthVerifyTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_VerifyEmail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthVerifyEmailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).VerifyEmail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.AuthService/VerifyEmail",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).VerifyEmail(ctx, req.(*AuthVerifyEmailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_Logout_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthLogoutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).Logout(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.AuthService/Logout",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).Logout(ctx, req.(*AuthLogoutRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_ForgotPassword_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthForgotPasswordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).ForgotPassword(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.AuthService/ForgotPassword",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).ForgotPassword(ctx, req.(*AuthForgotPasswordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_RecoverPassword_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthRecoverPasswordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).RecoverPassword(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.AuthService/RecoverPassword",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).RecoverPassword(ctx, req.(*AuthRecoverPasswordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _AuthService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.AuthService",
	HandlerType: (*AuthServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetByToken",
			Handler:    _AuthService_GetByToken_Handler,
		},
		{
			MethodName: "Login",
			Handler:    _AuthService_Login_Handler,
		},
		{
			MethodName: "Signup",
			Handler:    _AuthService_Signup_Handler,
		},
		{
			MethodName: "VerifyToken",
			Handler:    _AuthService_VerifyToken_Handler,
		},
		{
			MethodName: "VerifyEmail",
			Handler:    _AuthService_VerifyEmail_Handler,
		},
		{
			MethodName: "Logout",
			Handler:    _AuthService_Logout_Handler,
		},
		{
			MethodName: "ForgotPassword",
			Handler:    _AuthService_ForgotPassword_Handler,
		},
		{
			MethodName: "RecoverPassword",
			Handler:    _AuthService_RecoverPassword_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "auth.proto",
}
